css: |
  .global-section banner {
     margin-top: 30px;
     margin-left: 30px;
     margin-right: 30px;
     border-radius: 10px;
  }

  .global-section banner-text-overlay {
     margin: 30px;
     padding: 20px;
  }

  .global-section banner-text {
     padding: 50px;
     text-shadow: 1px 1px 4px rgba(0, 0, 5, 1);
  }

  .global-section title {
    text-shadow: 1px 1px 4px rgba(0, 0, 5, 1);
  }

  .global-section subtitle {
    font-weight: 400;
    text-shadow: 4px 4px 8px rgba(0, 0, 5, 1);
  }

  .global-section app-tile > button {
    background-color: alpha(white, 0.1);
  }

  .global-section {
    margin: 15px;
    border-radius: 25px;
    color: #ffffff;
  }

  .rec-section {
    background: linear-gradient(0deg, #80cfe3, #54a3d8);
  }

  .rec-section app-tile-installed-indicator {
    color: #2d2f9b;
  }

  .rec-section-dark {
    background: linear-gradient(0deg, #271e7f, #60a5c3);
  }

  .rec-section-dark app-tile-installed-indicator {
    color: #a8e6ff;
  }

  .cc-section {
    background: linear-gradient(0deg, #b8a0cf, #9b59b6);
  }

  .cc-section app-tile-installed-indicator {
    color: #000a55;
  }

  .cc-section-dark {
    background: linear-gradient(0deg, #392946, #050815);
  }

  .cc-section-dark app-tile-installed-indicator {
    color: #dbcaf3;
  }

  .music-section {
    background: linear-gradient(to bottom, #F56217, #ffab7b);
  }

  .music-section app-tile-installed-indicator {
    color: #4b5b64;
  }

  .music-section-dark {
    background: linear-gradient(to bottom, #F56217, #912906);
  }

  .music-section-dark app-tile-installed-indicator {
    color: #ffe6df;
  }

  .office-section {
    background: linear-gradient(to bottom, #ff3e82, #f7caf0);
  }

  .office-section app-tile-installed-indicator {
    color: #4a0052;
  }

  .office-section-dark {
    background: linear-gradient(to bottom, #750051, #fa486b);
  }

  .office-section-dark app-tile-installed-indicator {
    color: #007fd9;
  }

  .gaming-section {
    background: linear-gradient(0deg, #888a90, #67c29a);
  }

  .gaming-section app-tile-installed-indicator {
    color: #355c00;
  }

  .gaming-section-dark {
    background: linear-gradient(0deg, #003a00, #444445);
  }

  .gaming-section-dark app-tile-installed-indicator {
    color: #ffffff;
  }

  .utilities-section {
    background: linear-gradient(0deg, #888a90, #48659a);
  }

  .utilities-section app-tile-installed-indicator {
    color: #002542;
  }

  .utilities-section-dark {
    background: linear-gradient(to right bottom, #00389e, #1d3283, #242d6a, #262851, #24233a, #282636, #2b2a31, #2d2d2d, #3a3a3a, #474748, #555556, #646364);
  }

  .utilities-section-dark app-tile-installed-indicator {
    color: #dddddc;
  }

  .dev-section {
    background-image: linear-gradient(to right bottom, #8b6fab, #7a77b3, #687fb6, #5985b6, #4d8bb3, #4892b4, #4698b3, #499eb1, #4da8b3, #55b2b4, #61bbb4, #6fc4b3);
  }

  .dev-section app-tile-installed-indicator {
    color: #9b59b6;
  }

  .dev-section-dark {
    background: linear-gradient(to right bottom, #8b6fab, #7a68a6, #6861a0, #555a9a, #405494, #315c9a, #1f649e, #006ca1, #0084ac, #089ab1, #43b0b2, #6fc4b3);
  }

  .dev-section-dark app-tile-installed-indicator {
    color: #8c007c;
  }

  .ai-section {
    background: linear-gradient(0deg, #cc773e, #d05a00);
  }

  .ai-section app-tile-installed-indicator {
    color: #002c55;
  }

  .ai-section-dark {
    background: linear-gradient(0deg, #4a1c00, #eb8000);
  }

  .ai-section-dark app-tile-installed-indicator {
    color: #577bad;
  }

sections:
  - title: "Aurora Recommends"
    subtitle: "Our Favorite Applications"
    rows: 3
    banner: file:///run/host/etc/bazaar/01-aurora-bazaar.jxl
    banner-fit: cover
    banner-text-halign: start
    banner-text-valign: center
    banner-height: 400
    classes:
      - global-section
    light-classes:
      - rec-section
    dark-classes:
      - rec-section-dark
    appids:
      - io.github.DenysMb.Kontainer
      - com.pixelomer.ShijimaQt
      - org.kde.kstars
      - re.sonny.Eloquent
      - io.github.halfmexican.Mingle
      - org.kde.audiotube
      - io.github.getnf.embellish
      - io.github.pleromix.IceBox
      - io.github.nozwock.Packet
      - com.github.ADBeveridge.Raider
      - rocks.shy.VacuumTube
      - com.github.PintaProject.Pinta

  - title: "Content Creation"
    subtitle: "Create your first donut or make some tunes"
    rows: 2
    banner: file:///run/host/etc/bazaar/02-aurora-bazaar.jxl
    banner-fit: cover
    banner-text-halign: end
    banner-text-valign: center
    banner-height: 400
    classes:
      - global-section
    light-classes:
      - cc-section
    dark-classes:
      - cc-section-dark
    appids:
      - org.kde.krita
      - org.ardour.Ardour
      - org.kde.kdenlive
      - org.blender.Blender
      - org.inkscape.Inkscape
      - org.audacityteam.Audacity
      - com.obsproject.Studio
      - com.inochi2d.inochi-session
      - org.gimp.GIMP
      - org.darktable.Darktable
      - com.feaneron.Boatswain

  - title: "Music & Media"
    subtitle: "Let me break it down for you"
    rows: 2
    banner: file:///run/host/etc/bazaar/03-aurora-bazaar.jxl
    banner-fit: cover
    banner-text-halign: start
    banner-text-valign: center
    banner-height: 400
    classes:
      - global-section
    light-classes:
      - music-section
    dark-classes:
      - music-section-dark
    appids:
      - org.kde.elisa
      - com.spotify.Client
      - com.mastermindzh.tidal-hifi
      - org.videolan.VLC
      - com.github.iwalton3.jellyfin-media-player
      - tv.plex.PlexDesktop
      - org.kde.kasts
      - org.kde.arianna
      - com.plexamp.Plexamp
      - io.github.mhogomchungu.media-downloader
      - com.github.wwmm.easyeffects
      - me.timschneeberger.jdsp4linux

  - title: "Office & Productivity"
    subtitle: "Let's do some work"
    rows: 3
    banner: file:///run/host/etc/bazaar/04-aurora-bazaar.jxl
    banner-fit: cover
    banner-text-halign: end
    banner-text-valign: center
    banner-height: 400
    classes:
      - global-section
    light-classes:
      - office-section
    dark-classes:
      - office-section-dark
    appids:
      - com.slack.Slack
      - md.obsidian.Obsidian
      - org.onlyoffice.desktopeditors
      - org.libreoffice.LibreOffice
      - io.github.alainm23.planify
      - io.github.nokse22.Exhibit
      - io.gitlab.theevilskeleton.Upscaler
      - com.bambulab.BambuStudio
      - com.github.IsmaelMartinez.teams_for_linux
      - com.super_productivity.SuperProductivity

  - title: "Games"
    subtitle: "The cake is a lie"
    rows: 3
    banner: file:///run/host/etc/bazaar/05-aurora-bazaar.jxl
    banner-fit: cover
    banner-text-halign: start
    banner-text-valign: center
    banner-height: 400
    classes:
      - global-section
    light-classes:
      - gaming-section
    dark-classes:
      - gaming-section-dark
    appids:
      - com.valvesoftware.Steam
      - com.valvesoftware.SteamLink
      - com.heroicgameslauncher.hgl
      - io.github.Faugus.faugus-launcher
      - net.lutris.Lutris
      - org.vinegarhq.Sober
      - com.dec05eba.gpu_screen_recorder
      - com.github.Matoking.protontricks
      - org.prismlauncher.PrismLauncher
      - com.discordapp.Discord
      - com.parsecgaming.parsec
      - net.davidotek.pupgui2
      - org.endlessaccess.threadbare
      - net.supertuxkart.SuperTuxKart
      - com.github.k4zmu2a.spacecadetpinball
      - net.stabyourself.nottetris2

  - title: "Utilities"
    subtitle: "Stuff you didn't need until now"
    rows: 2
    banner: file:///run/host/etc/bazaar/06-aurora-bazaar.jxl
    banner-fit: cover
    banner-text-halign: end
    banner-text-valign: center
    banner-height: 400
    classes:
      - global-section
    light-classes:
      - utilities-section
    dark-classes:
      - utilities-section-dark
    appids:
      - app.drey.Warp
      - org.localsend.localsend_app
      - com.github.zocker_160.SyncThingy
      - org.keepassxc.KeePassXC
      - io.github.nokse22.asciidraw
      - io.github.radiolamp.mangojuice
      - org.fedoraproject.MediaWriter
      - org.gnome.gitlab.YaLTeR.VideoTrimmer
      - org.raspberrypi.rpi-imager
      - org.kde.optiimage
      - org.mozilla.vpn
      - hu.irl.cameractrls
      - org.gnome.gitlab.YaLTeR.Identity
      - io.github.BuddySirJava.SSH-Studio
      - au.stevetech.yafi
      - io.github.pwr_solaar.solaar

  - title: "Developers"
    subtitle: "Developers, developers, developers!"
    rows: 2
    banner: file:///run/host/etc/bazaar/07-aurora-bazaar.jxl
    banner-fit: cover
    banner-text-halign: start
    banner-text-valign: center
    banner-height: 400
    classes:
      - global-section
    light-classes:
      - dev-section
    dark-classes:
      - dev-section-dark
    appids:
      - io.podman_desktop.PodmanDesktop
      - io.kinvolk.Headlamp
      - org.gnome.Builder
      - com.getpostman.Postman
      - org.kde.kdevelop
      - io.dbeaver.DBeaverCommunity
      - org.gitfourchette.gitfourchette
      - com.mardojai.ForgeSparks
      - com.github.marhkb.Pods
      - cc.arduino.IDE2
      - io.github.plrigaux.sysd-manager
      - me.iepure.devtoolbox

  - title: "AI and Machine Learning"
    subtitle: "Experience the best of open source AI"
    rows: 1
    banner: file:///run/host/etc/bazaar/08-aurora-bazaar.jxl
    banner-fit: cover
    banner-text-halign: start
    banner-text-valign: center
    banner-height: 500
    classes:
      - global-section
    light-classes:
      - ai-section
    dark-classes:
      - ai-section-dark
    appids:
      - com.jeffser.Alpaca
      - io.github.qwersyk.Newelle
