name: Latest Images HWE
on:
  merge_group:
  pull_request:
    branches:
      - main
      - testing
    paths-ignore:
      - "**.md"
      - "iso_files/**"
      - "aurora_flatpaks/**"
      - "dx_flatpaks/**"
      - ".github/workflows/*iso*"
  workflow_call:
  workflow_dispatch:

jobs:
  build-image-latest:
    name: Build Latest Images
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        brand_name: ["aurora"]
    with:
      image_flavors: '["hwe", "hwe-nvidia", "hwe-nvidia-open"]'
      brand_name: ${{ matrix.brand_name }}
      stream_name: latest
      #kernel_pin: 6.12.12-207.bazzite.fc41.x86_64

  generate-release:
    name: Generate Release
    needs: [build-image-latest]
    secrets: inherit
    uses: ./.github/workflows/generate-release.yml
    with:
      stream_name: '["latest"]'
