name: Validate Justfiles

on:
  pull_request:
    paths:
      - "Justfile"
      - "just/*"
  push:
    branches:
      - main
    paths:
      - "Justfile"
      - "just/*"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Just
        uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b # v3

      - name: Check Just Syntax
        shell: bash
        run: |
          just check
